### ISSUE TITLE
"field" parameter on icingabeat-notifications Dashboard

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingabeat#12]
Errors with "field" parameter on icingabeat-notifications Dashboard, see attached screenshot.
Version: 1.1.0
![icingabeat-notifications](https://cloud.githubusercontent.com/assets/3973350/25481217/72758a0a-2b4c-11e7-9540-6c3f4699ff95.png)

**Comment by mwaldmueller** [comment]
More info...
![icingabeat-notifications2](https://cloud.githubusercontent.com/assets/3973350/25481301/d09bea7a-2b4c-11e7-98a1-3ea334d75812.png)

**Comment by bobapple** [comment]
When you do a refresh of the index-pattern and some of the fields don't have any data, they will be removed from Kibanas cache. This leads to an error in a Kibana visualization that references the removed field.

How to reproduce:
- Import icingabeat-dashboards
- Start icingabeat without event type `Notification`
- Refresh index-pattern
=> Since you don't have any data for the field `notification_type` Kibana removes the field from its cache. This is actually a correct behaviour, but dashboards/visualizations referencing this field break.
